### ISSUE TITLE
Compile errors when using wasmer-wasi in a workspace

### ISSUE THREAD

**Issue by juchiast** [wasmerio/wasmer#3377]
### Describe the bug

Compile errors when a member of workspace depends on wasmer-wasi

### Steps to reproduce

```
rustc --version
rustc 1.65.0 (897e37553 2022-11-02)
```

```
.
├── Cargo.lock
├── Cargo.toml
└── wasm-cmds
    ├── Cargo.toml
    └── src
        └── main.rs
```

`Cargo.toml`:

```toml
[workspace]
members = ["wasm-cmds"]
```

`wasm-cmds/Cargo.toml`:

```
[package]
name = "wasm-cmds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-wasi = "3.0.1"
```

`Cargo.lock`: https://gist.github.com/juchiast/8f003f152a3fd99d8e093599644cc335

### Actual behavior

`cargo check` failed with a lot of compile errors,  I can't read all of them but most are `js` and `sys` module conflicting with each other.

```
    Checking wasmer v3.0.1
error[E0428]: the name `imports` is defined multiple times
   --> /home/qwe/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.0.1/src/js/imports.rs:355:1
    |
355 | macro_rules! imports {
    | ^^^^^^^^^^^^^^^^^^^^ `imports` redefined here
    |
   ::: /home/qwe/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.0.1/src/sys/imports.rs:227:1
    |
227 | macro_rules! imports {
    | -------------------- previous definition of the macro `imports` here
    |
    = note: `imports` must be defined only once in the macro namespace of this module

error[E0428]: the name `namespace` is defined multiple times
   --> /home/qwe/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.0.1/src/js/imports.rs:373:1
    |
373 | macro_rules! namespace {
    | ^^^^^^^^^^^^^^^^^^^^^^ `namespace` redefined here
    |
   ::: /home/qwe/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.0.1/src/sys/imports.rs:245:1
    |
245 | macro_rules! namespace {
    | ---------------------- previous definition of the macro `namespace` here
    |
    = note: `namespace` must be defined only once in the macro namespace of this module

.....................

error: could not compile `wasmer` due to 226 previous errors
```

```
     Running `CARGO=/home/qwe/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME=wasmer CARGO_MANIFEST_DIR=/home/qwe/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.0.1 CARGO_PKG_AUTHORS='Wasmer Engineering Team <engineering@wasmer.io>' CARGO_PKG_DESCRIPTION='High-performance WebAssembly runtime' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=wasmer CARGO_PKG_REPOSITORY='https://github.com/wasmerio/wasmer' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=3.0.1 CARGO_PKG_VERSION_MAJOR=3 CARGO_PKG_VERSION_MINOR=0 CARGO_PKG_VERSION_PATCH=1 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/home/qwe/check/target/debug/deps:/home/qwe/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib:/home/qwe/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib' rustc --crate-name wasmer --edition=2018 /home/qwe/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-3.0.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata -C embed-bitcode=no -C debuginfo=0 --cfg 'feature="compiler"' --cfg 'feature="js"' --cfg 'feature="js-sys"' --cfg 'feature="sys"' --cfg 'feature="wasm-bindgen"' --cfg 'feature="wat"' -C metadata=07c492f3608cd047 -C extra-filename=-07c492f3608cd047 --out-dir /home/qwe/check/target/debug/deps -C linker=clang -L dependency=/home/qwe/check/target/debug/deps --extern bytes=/home/qwe/check/target/debug/deps/libbytes-97a29d31fae18d55.rmeta --extern cfg_if=/home/qwe/check/target/debug/deps/libcfg_if-226410e8bb85edcd.rmeta --extern indexmap=/home/qwe/check/target/debug/deps/libindexmap-988c1b5ff575b4d6.rmeta --extern js_sys=/home/qwe/check/target/debug/deps/libjs_sys-f76c46828b6bd37e.rmeta --extern more_asserts=/home/qwe/check/target/debug/deps/libmore_asserts-3e8c75cc94f1efa7.rmeta --extern target_lexicon=/home/qwe/check/target/debug/deps/libtarget_lexicon-35052bd4b2eb79fb.rmeta --extern thiserror=/home/qwe/check/target/debug/deps/libthiserror-cbb1ef0dfc6bcd39.rmeta --extern wasm_bindgen=/home/qwe/check/target/debug/deps/libwasm_bindgen-1eba225586516832.rmeta --extern wasmer_compiler=/home/qwe/check/target/debug/deps/libwasmer_compiler-d1adf63979e52dba.rmeta --extern wasmer_derive=/home/qwe/check/target/debug/deps/libwasmer_derive-2d275e347e7f7c4b.so --extern wasmer_types=/home/qwe/check/target/debug/deps/libwasmer_types-6e04a323e2c0a18e.rmeta --extern wasmer_vm=/home/qwe/check/target/debug/deps/libwasmer_vm-d14b498af80f0d02.rmeta --extern wat=/home/qwe/check/target/debug/deps/libwat-a05b19ea6b68e5d3.rmeta --cap-lints warn -C link-arg=-fuse-ld=/usr/bin/mold`
```

This part: `--cfg 'feature="js"' --cfg 'feature="js-sys"' --cfg 'feature="sys"'` is wrong and I don't know why it's there.

### Additional context

It can compile normally if the crate is not a member of any workspace, so this works:

```toml
[workspace]
members = []

exclude = ["wasm-cmds"]
```

Probably a bug with cargo, I'll go and report over there too.

**Comment by juchiast** [comment]
I could compile with `3.0.0-rc.1`, but since `3.0.0-rc.2` it stopped working.

**Comment by Michael-F-Bryan** [comment]
It looks like something in your dependency tree is enabling the `js` and `sys` feature flags, but they are meant to be mutually exclusive features. 

The `sys-default` feature is enabled by default, so if you want to use Wasmer in the browser, you'll need to enable the `js-default` feature and disable `sys-default`. You can do this by modifying your `Cargo.toml` to include `wasmer-wasi = { version = "3.0.1", default-features = false, features = ["js-default"] }` .

There used to be a check which emitted a `compile_error!()` when both `sys` and `js` are enabled, but this might have been accidentally removed recently.

CC: @theduke

**Comment by RReverser** [comment]
Running into this as well and it's driving me crazy, because I checked Cargo.lock, Rust logs etc. and there's nothing indicating what enables the "js" feature.

And it all works fine unless I add `wasmer-wasi` as a dependency. `wasmer-wasi` doesn't have `js` feature enabled by default either, so it doesn't make sense why simply adding it a dependency would suddenly make `wasmer` have both `sys` and `js` enabled, while without it it's just `sys`.

And I can't even reproduce this on an empty project :/

> There used to be a check which emitted a `compile_error!()` when both `sys` and `js` are enabled, but this might have been accidentally removed recently.

Yeah it's still there, but Cargo tries to be "helpful" and keeps compiling, so the error message ends up lost among actual compilation errors. Maybe it should emit the error in `build.rs` or something instead?

**Comment by RReverser** [comment]
Oh, and my project does use `resolver = "2"`.

**Comment by RReverser** [comment]
> As EHuss mentioned in the linked issue, we should also enable `resolver = "2"` or upgrade to the 2021 edition.
> 
> > It looks like wasmer-wasi requires resolver = "2" to be configured for it to work with the default feature set. You can set that in your [workspace] definition. I suspect they just haven't tested with that particular combination of feature flags enabled.

...huh. Reading this a bit more closely, I tried setting `resolver = "2"` in the workspace Cargo.toml, even though the actual crates in the workspace were already on `edition = "2021"` / `resolver = "2"` and that seems to make a difference somehow?

It doesn't make any sense, but now it builds :/

**Comment by RReverser** [comment]
Right, just tried in a local fork and looks like adding `resolver = "2"` in wasmer itself is enough to fix the issue regardless of the `resolver` used in my own workspace.

**Comment by outkine** [comment]
Just confirming that this was an issue for me, and setting `resolver = "2"` addresses it

**Comment by theduke** [comment]
For posterity: 

Setting ` resolver = "2"` in your workspace `Cargo.toml` should resolve the problem.
The Wasmer workspace now also uses ` resolver = "2"`.
