### PR TITLE
chore(lib/vm): update `corosensei` to `0.3.0` to support AddressSanitizer

### PR DESCRIPTION
**Pull request by StackOverflowExcept1on**
# Description

See #5746

### CODE REVIEW

**Comment by syrusakbary** [comment]
Thanks for the PR.
As @Amanieu commented on the original issue we would need to use the ScopedCoroutine when upgrading to 0.3.0
https://github.com/wasmerio/wasmer/issues/5721#issuecomment-3342127298

**Comment by StackOverflowExcept1on** [comment]
@syrusakbary thx for quick reply!
```
    Checking wasmer-vm v6.1.0-rc.5 (/mnt/tmpfs/wasmer/lib/vm)
error[E0597]: `stack` does not live long enough
   --> lib/vm/src/trap/traphandlers.rs:953:48
    |
950 |       let mut stack = scopeguard::guard(stack, |stack| STACK_POOL.push(stack));
    |           --------- binding `stack` declared here
...
953 |       let mut coro = Coroutine::with_stack(&mut *stack, move |yielder, ()| {
    |                      -                           ^^^^^ borrowed value does not live long enough
    |  ____________________|
    | |
954 | |         // Save the yielder to TLS so that it can be used later.
955 | |         YIELDER.with(|cell| cell.set(Some(yielder.into())));
...   |
958 | |     });
    | |______- argument requires that `stack` is borrowed for `'static`
...
980 |   }
    |   - `stack` dropped here while still borrowed

For more information about this error, try `rustc --explain E0597`.
error: could not compile `wasmer-vm` (lib) due to 1 previous error
```
looks like we also need to fix stack caching somehow

**Comment by StackOverflowExcept1on** [comment]
@syrusakbary done! I checked API changes in benchmarks here: https://github.com/Amanieu/corosensei/pull/58, https://github.com/Amanieu/corosensei/pull/60.

**Comment by syrusakbary** [comment]
In general it looks good to me (I wonder if it might be better to do `coro.scope` inside the Trap handler instead of outside). @Amanieu I'd love to hear your thoughts!

Note: the tests failing have nothing to do with the code changes from this PR

**Comment by Amanieu** [comment]
It makes no difference, the scope is just there to ensure the coroutine is properly dropped at the end of the scope. This code is fine as it is.
